################################################################################
# Phylogenetic trait imputation
#
# Purpose:
# Impute missing functional trait values using phylogenetic information with
# Rphylopars.
#
# Inputs:
#   output_tree5.tre                    - Phylogenetic tree
#   PreImputationData_transformed2.csv  - Trait dataset used for imputation
#
# Outputs:
#   imputedtraitsdata.csv         - Imputed trait estimates
#   
#
# Following imputation, imputed values falling outside the observed range of
# the corresponding trait were treated as missing. This screening step was
# performed after the outputs generated by this script. The imputed traits were
# merged with the remaining traits and variables from the original dataset.
################################################################################

library(ape)
library(Rphylopars)

# Read input files
myTree <- read.tree("Data/AnalysisPhylogeny.tre")

traitdata <- read.csv("Data/TraitImputationInput.csv")

# Perform phylogenetic trait imputation
p_BM <- phylopars(trait_data = traitdata,tree = myTree)

# Extract imputed trait estimates for the study species
imp_data <- as.data.frame(p_BM$anc_recon[seq_len(nrow(traitdata)),])

# Export imputed trait estimates
write.csv(imp_data,"Data/ImputedTraitData.csv")

